name: Free Windows Remote Access

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Ngrok
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path "ngrok.zip" -DestinationPath "$env:USERPROFILE\ngrok"
          Get-ChildItem "$env:USERPROFILE\ngrok" # Debug: Cek isi folder setelah ekstrak
          Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\ngrok\ngrok.exe" -ArgumentList "authtoken 2ulenCULFgHp45RwYTMHprHN2x4_7yu1YyFMLZPZW8C3y2gVG"
          Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\ngrok\ngrok.exe" -ArgumentList "tcp 3389"
        shell: powershell

      - name: Enable RDP and Firewall
        run: |
          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          netsh advfirewall firewall set rule group="remote desktop" new enable=yes
          net localgroup Administrators runneradmin /add
          net user runneradmin MySecurePassword123!
        shell: cmd

      - name: Get Ngrok Address
        run: Get-Content "$env:USERPROFILE\ngrok\ngrok.log"
        shell: powershell
