name: Setup Cloudflare Tunnel

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Cloudflare Tunnel
        run: |
          Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"
          Move-Item -Path "cloudflared.exe" -Destination "$env:USERPROFILE\cloudflared.exe"
        shell: powershell

      - name: Authenticate Cloudflare Tunnel with Token
        run: |
          $cloudflared = "$env:USERPROFILE\cloudflared.exe"
          & $cloudflared service install
          & $cloudflared tunnel --token YOUR_CLOUDFLARE_TUNNEL_TOKEN
        shell: powershell
        env:
          CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}

      - name: Start Cloudflare Tunnel for RDP
        run: |
          $cloudflared = "$env:USERPROFILE\cloudflared.exe"
          Start-Process -NoNewWindow -FilePath $cloudflared -ArgumentList "tunnel run"
        shell: powershell
