name: Setup RDP via Ngrok

on: 
  workflow_dispatch  # Menjalankan workflow secara manual

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup RDP
      run: |
        Enable-PSRemoting -Force
        net user github "Github@1234" /add
        net localgroup Administrators github /add
        netsh advfirewall set allprofiles state off
        Set-ItemProperty 'HKLM:\System\CurrentControlSet\Control\Terminal Server\' -Name "fDenyTSConnections" -Value 0
        Get-NetFirewallRule -DisplayGroup "Remote Desktop" | Set-NetFirewallRule -Enabled True
        Install-WindowsFeature -Name RDS-RD-Server -IncludeAllSubFeature -IncludeManagementTools

    - name: Download Ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive ngrok.zip -DestinationPath "$env:USERPROFILE\ngrok"

    - name: Start Ngrok Tunnel
      env:
        NGROK_AUTH_TOKEN: ${{ 2ulvPqxYS3YdaQOMNwHJ6rwFdxe_6SshAstYuoRTFmAbN4A7E }}
      run: |
        Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\ngrok\ngrok.exe" -ArgumentList "authtoken $env:NGROK_AUTH_TOKEN"
        Start-Process -NoNewWindow -FilePath "$env:USERPROFILE\ngrok\ngrok.exe" -ArgumentList "tcp 3389"
        Start-Sleep -s 10
        Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels"

    - name: Keep Alive
      run: |
        while ($true) { Start-Sleep -s 3600 }
