name: Free RDP Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          netsh advfirewall firewall set rule group="remote desktop" new enable=yes
          powershell.exe -ExecutionPolicy Bypass -Command "& {Enable-PSRemoting -Force}"
          powershell.exe -ExecutionPolicy Bypass -Command "& {Start-Service termservice}"
          net user runneradmin MySecurePassword123!
